# configMapGenerator:
# - name: game-config-5
#   options:
#     labels:
#       game-config: config-5
#   files:
#   - game-special-key=./configmap/game.properties
configMapGenerator:
- name: special-config-2
  literals:
  - special.how=very
  - special.type=charm